import type { Metadata } from "next";
import { Geist, Geist_Mono, Kalam } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import { ReduxProvider } from "@/hooks/IsPhone";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const kalam = Kalam({
  variable: "--font-kalam",
  subsets: ["devanagari", "latin"],
  weight: ["400", "700"],
});

const nibpro = localFont({
  src: "./fonts/nibpro.ttf",
  variable: "--font-nibpro",
});

const nibprobold = localFont({
  src: "./fonts/nibproBold.ttf",
  variable: "--font-nibproBold",
});

const stickers = localFont({
  src: "./fonts/stickers.otf",
  variable: "--font-stickers",
});

const rango = localFont({
  src: "./fonts/rango.otf",
  variable: "--font-rango",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Combine all font variables into one class name
const combinedFontClassName = `
  ${geistSans.variable} 
  ${geistMono.variable} 
  ${nibpro.variable} 
  ${nibprobold.variable} 
  ${stickers.variable} 
  ${rango.variable} 
  ${kalam.variable}
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${combinedFontClassName} antialiased`}>
        <ReduxProvider>
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
